mptcp: fastopen: client-MSG_FASTOPEN.pkt
multipath-tcp/packetdrill pull request #99
Opened 2022-11-06 20:47 UTC by dmytroshytyi

This commit adds feature to test client-MSG_FASTOPEN.

Tested on  by doing the following:
root@(none):/opt/packetdrill/gtests/net# ./packetdrill/run_all.py -S -v -L -l ./mptcp/fastopen/client-MSG_FASTOPEN.pkt
OK   [/opt/packetdrill/gtests/net/mptcp/fastopen/client-MSG_FASTOPEN.pkt (ipv4)]
stdout:
stderr:
OK   [/opt/packetdrill/gtests/net/mptcp/fastopen/client-MSG_FASTOPEN.pkt (ipv6)]
stdout:
stderr:
OK   [/opt/packetdrill/gtests/net/mptcp/fastopen/client-MSG_FASTOPEN.pkt (ipv4-mapped-v6)]
stdout:
stderr:
Ran    3 tests:    3 passing,    0 failing,    0 timed out (7.24 sec): ./mptcp/fastopen/client-MSG_FASTOPEN.pkt

Signed-off-by: Dmytro Shytyi <github.dmytro@shytyi.net>

2022-11-07 16:50 UTC, matttbe commented
Hi Dmytro,

Thank you for the PR.

Do you need to change the content of the file? I see it is still doing the same from an MPTCP point of view.

If you do need to modify the content, please explain that in the commit message and keep the alignment with the previous lines, see the end of the `README.md` file for more details.

2022-11-07 16:52 UTC, matttbe commented
Also, I see there are other `.TODO` files linked to `MSG_FASTOPEN`:

```bash
$ ls -1 mptcp/fastopen/*.TODO
mptcp/fastopen/client-MSG_FASTOPEN-no-cookie.pkt.TODO
mptcp/fastopen/client-MSG_FASTOPEN-no-cookie-rejected.pkt.TODO
mptcp/fastopen/client-MSG_FASTOPEN.pkt.TODO
```

Next step would be to have packetdrill tests for the server side ;)

2022-11-07 16:59 UTC, dmytroshytyi commented
Hello matttbe,

> Hi Dmytro,
> 
> Thank you for the PR.
> 
> Do you need to change the content of the file? I see it is still doing the same from an MPTCP point of view.

Yes, I had to change the content of the file. Without this modification, tests are failing. There is some difference that is introduced by suppressing the TSs. This influences the options padding and we need to reorganize "NOP"s.

 
> If you do need to modify the content, please explain that in the commit message and keep the alignment with the previous lines, see the end of the `README.md` file for more details.

okay, I will check the end of the `README`. Thank you for pointing on this.

2022-11-07 17:05 UTC, matttbe commented
> Yes, I had to change the content of the file. Without this modification, tests are failing ( which is expected IMHO).

I'm surprised because this test is very similar to `mptcp/fastopen/client-TCP_FASTOPEN_CONNECT.pkt` which works fine.

Please explain in the commit message why you have to modify the different lines.

2022-11-07 17:05 UTC, dmytroshytyi commented
> > Yes, I had to change the content of the file. Without this modification, tests are failing ( which is expected IMHO).
> 
> I'm surprised because this test is very similar to `mptcp/fastopen/client-TCP_FASTOPEN_CONNECT.pkt` which works fine.
> 
> Please explain in the commit message why you have to modify the different lines.

Ah I was actually writting the small explanation as "Edit message"... I will definitely do this. Please check my previous comment. Thanks.

2022-11-07 17:08 UTC, dmytroshytyi commented
> > Yes, I had to change the content of the file. Without this modification, tests are failing ( which is expected IMHO).
> 
> I'm surprised because this test is very similar to `mptcp/fastopen/client-TCP_FASTOPEN_CONNECT.pkt` which works fine.
> 
> Please explain in the commit message why you have to modify the different lines.

The TCP options space is not enough for both fastopen cookie and TimeStamps. I discovered it ~6 month ago with gdb.

2022-11-07 17:09 UTC, matttbe commented
> There is some difference that is introduced by suppressing the TSs.

Why do you need to remove TS? I don't think you need to when validating the client side, no?
I mean: depending on the cookie size, the listener might have enough space to keep the TSs like it is here, no?

It would be good to keep the tests for `TCP_FASTOPEN_CONNECT` and `MSG_FASTOPEN` in sync

2022-11-07 17:34 UTC, dmytroshytyi commented
Please correct me if I'm mistaken:
The TCP option space ==  40 bytes
Options space consumption:
MP_CAPABLE == 12 bytes
timestamp == 10 bytes
window scale == 3 bytes
SACK permitted = 2 bytes
Maximum Segment Size = 4 bytes
FASTOPEN cookie  = 10 bytes // And yes it can be variable (smaller), however, this is the size employed by linux impl. So probably it is better to stick to default size employed by linux impl.

As a result we are running out of options space.

2022-11-21 12:49 UTC, matttbe commented
@dmytroshytyi Sorry for the delay.

In the test you are modifying (`client-MSG_FASTOPEN.pkt`), we validate packets sent by the client side controlled by the kernel networking stack. The server side is controlled by Packetdrill which reads and injects/crafts packets from/to the Linux kernel.

In other words, here, the "server" side can do stuff the kernel is not able to. That's great to check the kernel is doing what we want, without even having to implement the server side support + check interoperability, reproduce/find bugs, etc.

Here, the test is correct as it is for me. Yes, it will use the 40 bytes of the TCP option space: MSS (4), SACK OK (2), Time Stamps (10), Window Scale (3+1), TFO (6+2), MP_CAPABLE (12).
So that's fine, no?

Of course, when we will want to validate the server side, we will not be able to do that but that's a different test.

So for me, we should not modify the test but only rename it to remove the `.TODO`. We can of course add another test not including the TS part but that will be a different test, it should not replace the existing one. Do you want to do that?

Also, do you still plan to add tests to cover the server part?

2022-11-21 12:50 UTC, matttbe requested changes
(see my previous comment: only removing the .TODO is needed but we can add a new test without TS)

2022-11-21 16:04 UTC, matttbe commented
@dmytroshytyi I was looking at eventually adding `TCP_FASTOPEN_KEY`. While on it, I already did the renaming to remove the `.TODO`, see #102.

We can keep this PR here opened to add one test without Timestamps if that's OK for you

2023-12-15 09:54 UTC, matttbe commented
> We can keep this PR here opened to add one test without Timestamps if that's OK for you

Even if this task still needs to be done, I suggest to close this PR. We can re-open a new one if someone wants to add a test for this case.

2023-12-15 09:54 UTC, closed without merging